### ISSUE TITLE
spodr status fails

### ISSUE THREAD

**Issue by oliversalzburg** [fairmanager/spodr#8]
```shell
2017-05-15 15:55:16.169 [ERROR ] (          app) ReferenceError: fetchRepos is not defined
2017-05-15 15:55:16.169                              at new GitStatusTask (D:\spodr\lib\tasks\task.git-status.js:22:21)
2017-05-15 15:55:16.169                              at Object.taskFactory [as gitStatus] (D:\spodr\lib\tasks\task.git-status.js:97:15)
2017-05-15 15:55:16.169                              at Promise.resolve.then.fetchRepos (D:\spodr\lib\app.js:206:31)
2017-05-15 15:55:16.169                              at tryCatcher (D:\spodr\node_modules\bluebird\js\release\util.js:16:23)
2017-05-15 15:55:16.169                              at Promise._settlePromiseFromHandler (D:\spodr\node_modules\bluebird\js\release\promise.js:510:31)
2017-05-15 15:55:16.169                              at Promise._settlePromise (D:\spodr\node_modules\bluebird\js\release\promise.js:567:18)
2017-05-15 15:55:16.169                              at Promise._settlePromiseCtx (D:\spodr\node_modules\bluebird\js\release\promise.js:604:10)
2017-05-15 15:55:16.169                              at Async._drainQueue (D:\spodr\node_modules\bluebird\js\release\async.js:143:12)
2017-05-15 15:55:16.169                              at Async._drainQueues (D:\spodr\node_modules\bluebird\js\release\async.js:148:10)
2017-05-15 15:55:16.169                              at Immediate.Async.drainQueues (D:\spodr\node_modules\bluebird\js\release\async.js:17:14)
2017-05-15 15:55:16.169                              at runCallback (timers.js:672:20)
2017-05-15 15:55:16.169                              at tryOnImmediate (timers.js:645:5)
2017-05-15 15:55:16.169                              at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by reck1610** [comment]
already fixed
